import {chromium} from 'playwright';
import {resolve} from 'node:path';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {homedir} from 'node:os';
import {sampleText} from '../src/core.js';
const runtime=createRequire(resolve(process.env.TIANYA_FIXTURE_MODULES || resolve(homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node'),'package.json'));
const {PDFDocument,StandardFonts}=runtime('pdf-lib');
const {Document,Packer,Paragraph}=runtime('docx');
const out=resolve('../../outputs'),extension=resolve(out,'tianya-extension');
await mkdir(resolve(out,'screenshots'),{recursive:true});
const browser=await chromium.launchPersistentContext(resolve('.browser-test-profile'),{executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,viewport:{width:440,height:940},args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});
const passed=[],errors=[],requests=[];
let panel;
try{
 const worker=browser.serviceWorkers()[0]||await browser.waitForEvent('serviceworker');
 const id=worker.url().split('/')[2];
 await worker.evaluate(()=>Promise.all([chrome.storage.local.clear(),chrome.storage.session.clear()]));
 panel=await browser.newPage();panel.on('pageerror',e=>errors.push(e.message));panel.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
 panel.on('dialog',d=>d.accept());
 await panel.goto(`chrome-extension://${id}/panel.html`);
 await panel.getByRole('heading',{name:'一份简历，反复使用。'}).waitFor();
 assert.deepEqual(await panel.locator('.tabs button').allTextContents(),['01我的简历','02填当前页']);passed.push('默认进入简历页且仅保留两个核心入口');
 await panel.screenshot({path:resolve(out,'screenshots/01-简历入口.png'),fullPage:true});
 const opened=browser.waitForEvent('page');await panel.getByRole('button',{name:'安全练习'}).click();const practice=await opened;await practice.waitForLoadState();practice.on('pageerror',e=>errors.push(e.message));
 await panel.getByRole('button',{name:'载入示例',exact:true}).click();
 await panel.getByRole('button',{name:'已校对，去填写'}).click();
 await panel.getByRole('button',{name:'识别当前页面',exact:true}).click();
 await panel.locator('.mapping').first().waitFor();
 assert.equal(await panel.locator('.mapping').count(),17);passed.push('识别到标准表单');console.log('PASS 识别到标准表单');
 await panel.getByLabel('关闭提示').click();await panel.evaluate(()=>scrollTo(0,0));await panel.screenshot({path:resolve(out,'screenshots/02-填写预览.png')});
 assert.equal(await panel.getByLabel('现居城市对应的简历字段').count(),0);passed.push('已有字段不进入待填列表');
 assert.equal(await panel.getByLabel('选择填写 结束日期',{exact:true}).isChecked(),false);passed.push('年月不猜测完整日期');
 assert.equal(await panel.getByLabel('选择填写 身份证号码',{exact:true}).isEnabled(),false);passed.push('敏感字段不可自动填');
 await panel.getByRole('button',{name:/确认填写 \d+ 项/}).click();
 await panel.getByText(/已写入并回读 \d+ 项，其余/).waitFor();
 assert.equal(await practice.getByLabel('姓名',{exact:true}).inputValue(),'林晓雨');passed.push('真实 DOM 写入姓名');
 assert.equal(await practice.locator('#react-value').innerText(),'React 已接收：林晓雨');passed.push('React controlled state 已更新');
 assert.equal(await practice.getByLabel('电子邮箱',{exact:true}).inputValue(),'xiaoyu@example.com');passed.push('邮箱写入');
 assert.equal(await practice.locator('select').inputValue(),'master');passed.push('原生下拉学历别名匹配');
 assert.equal(await practice.getByLabel('开始日期',{exact:true}).inputValue(),'2024-09');passed.push('月份输入写入');
 assert.equal(await practice.getByLabel('结束日期',{exact:true}).inputValue(),'');passed.push('不补猜完整日期');
 assert.equal(await practice.getByLabel('现居城市',{exact:true}).inputValue(),'此项已有内容，请保留');passed.push('已有内容保持原样');
 assert.equal(await practice.getByLabel('身份证号码',{exact:true}).inputValue(),'');passed.push('身份证留空');
 assert.equal(await practice.getByLabel('验证码',{exact:true}).inputValue(),'');passed.push('验证码留空');
 assert.equal(await practice.locator('input[type=checkbox]').isChecked(),false);passed.push('不勾选协议');
 assert.equal(await practice.getByText('你手动点击了检查。没有发生真实投递。').count(),0);passed.push('未提交表单');
 await practice.setViewportSize({width:1280,height:900});await practice.screenshot({path:resolve(out,'screenshots/03-填写结果.png'),fullPage:true});
 await practice.getByLabel('姓名',{exact:true}).fill('用户自行修改');
 await panel.getByRole('button',{name:'撤销上次填写'}).click();await panel.getByText(/已撤销 \d+ 项/).waitFor();
 assert.equal(await practice.getByLabel('姓名',{exact:true}).inputValue(),'用户自行修改');passed.push('撤销保留用户后续修改');
 assert.equal(await practice.getByLabel('电子邮箱',{exact:true}).inputValue(),'');passed.push('撤销恢复原空值');
 await panel.getByRole('button',{name:'01 我的简历'}).click();
 const fileInput=panel.getByLabel('选择简历文件',{exact:true});
 await fileInput.setInputFiles({name:'resume.txt',mimeType:'text/plain',buffer:Buffer.from(sampleText)});await panel.getByText(/已提取 \d+ 个字符/).waitFor();
 assert.ok((await panel.locator('textarea.source').inputValue()).includes('林晓雨'));passed.push('TXT 导入');
 const docx=await Packer.toBuffer(new Document({sections:[{children:sampleText.split('\n').map(t=>new Paragraph(t))}]}));
 await fileInput.setInputFiles({name:'resume.docx',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',buffer:docx});await panel.getByText(/已提取 \d+ 个字符/).waitFor();assert.ok((await panel.locator('textarea.source').inputValue()).includes('英语口译'));passed.push('DOCX 中文文字提取');
 const pdf=await PDFDocument.create(),page=pdf.addPage();page.drawText('Name: Test User\nEmail: resume@example.com',{x:40,y:700,size:14,font:await pdf.embedFont(StandardFonts.Helvetica)});
 await fileInput.setInputFiles({name:'resume.pdf',mimeType:'application/pdf',buffer:Buffer.from(await pdf.save())});await panel.getByText(/已提取 \d+ 个字符/).waitFor();assert.ok((await panel.locator('textarea.source').inputValue()).includes('resume@example.com'));passed.push('PDF 本地 worker 文字提取');
 const blank=await PDFDocument.create();blank.addPage();await fileInput.setInputFiles({name:'scan.pdf',mimeType:'application/pdf',buffer:Buffer.from(await blank.save())});await panel.getByRole('alert').filter({hasText:'未提取到文字'}).waitFor();passed.push('无文字 PDF 明确拒绝');
 await fileInput.setInputFiles({name:'broken.pdf',mimeType:'application/pdf',buffer:Buffer.from('not a pdf')});await panel.getByRole('alert').waitFor();passed.push('损坏 PDF 错误可见');
 await fileInput.setInputFiles({name:'resume.doc',mimeType:'application/msword',buffer:Buffer.from('test')});await panel.getByRole('alert').filter({hasText:'旧版 DOC'}).waitFor();passed.push('旧版 DOC 明确不支持');
 await panel.getByLabel('AI 与隐私设置').click();await panel.getByRole('button',{name:'保存设置并 AI 解析'}).click();await panel.getByRole('alert').filter({hasText:'同意'}).waitFor();passed.push('未同意云端发送时拦截');
 assert.equal(requests.length,0);passed.push('本地流程没有外部网络请求');
 await panel.getByRole('button',{name:'01 我的简历'}).click();await panel.setViewportSize({width:340,height:800});
 assert.equal(await panel.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);passed.push('340px 窄屏无横向溢出');await panel.screenshot({path:resolve(out,'screenshots/04-窄屏侧栏.png'),fullPage:true});
 await panel.setViewportSize({width:1280,height:900});assert.equal(await panel.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);passed.push('1280px 桌面布局');await panel.screenshot({path:resolve(out,'screenshots/05-桌面预览.png'),fullPage:true});
 await panel.reload();await panel.getByRole('button',{name:'01 我的简历'}).click();assert.equal(await panel.getByLabel('姓名',{exact:true}).inputValue(),'林晓雨');passed.push('简历本机存储跨刷新保留');
 assert.deepEqual(errors,[]);passed.push('无浏览器运行时错误');
 console.log(`PASS ${passed.length} browser checks; external requests ${requests.length}`);
 await writeFile(resolve('tests/browser-result.json'),JSON.stringify({date:new Date().toISOString(),browser:await browser.browser().version(),passed,errors,requests},null,2));
}catch(e){if(panel)await panel.screenshot({path:resolve(out,'screenshots/test-failure.png'),fullPage:true});console.error('BROWSER ERRORS',errors);throw e;}finally{await browser.close();}
